### all users
GET http://localhost:3000/auth/
### get one user by id
GET http://localhost:3000/auth/1
### user signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "shyna@gmail.com",
    "password": "shynah"
}
### user signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "shyna@gmail.com",
    "password": "shynah"
}
### user signout
GET http://localhost:3000/auth/signout

### whoami
GET http://localhost:3000/auth/whoami

### update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password" : "1234"
}

### delete a user
DELETE http://localhost:3000/auth/3